version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: activity_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clover@123
      MYSQL_DATABASE: activitydb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  django:
    build: .
    container_name: activity_django
    depends_on:
      - mysql
    command: >
      sh -c "
      echo 'Waiting for MySQL...' &&
      until nc -z mysql 3306; do
        sleep 2;
      done;
      echo 'MySQL is Ready!' &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: activitydb
      DB_USER: root
      DB_PASSWORD: clover@123
      DB_HOST: mysql
      DB_PORT: 3306

volumes:
  mysql_data:

